name: Add to Shift Ahoy Project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/shiftahoy/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}